/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nlt.view;

import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import static org.nlt.view.ParentInterface.connect;
import static org.nlt.view.ParentInterface.personFrame;
import static org.nlt.view.ParentInterface.projectTitle;

/**
 *
 * @author Hp
 */
public class ChangePasswordFrame extends javax.swing.JFrame implements ParentInterface{

    
    public ChangePasswordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        oldpasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        newpasswordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmpasswordField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 20, 20));

        jLabel2.setText("OLD PASSWORD");
        jPanel1.add(jLabel2);
        jPanel1.add(oldpasswordField);

        jLabel3.setText("NEW PASSWORD");
        jPanel1.add(jLabel3);
        jPanel1.add(newpasswordField);

        jLabel4.setText("CONFIRM PASSWORD");
        jPanel1.add(jLabel4);
        jPanel1.add(confirmpasswordField);

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
          try {
            String oldpassword = oldpasswordField.getText();
            String newpassword = newpasswordField.getText();
            String confirmNewpassword=confirmpasswordField.getText();
            
            Statement smt = connect.createStatement();
            ResultSet rs = smt.executeQuery("select * from users where email='" + personFrame.loginUserEmail + "'  and password='" + oldpassword + "' and status=1");


            if(rs.next()) 
            {
                if (newpassword.equals(confirmNewpassword)) {
                    smt.execute("update users set password='" + confirmNewpassword + "' where email='" + personFrame.loginUserEmail +"' and status=1");
                    JOptionPane.showMessageDialog(this, "Password Change Successfully ", projectTitle, JOptionPane.INFORMATION_MESSAGE);
                    Mailer.send("divyakatolkar@gmail.com", "fadephzjyeiasvlp", personFrame.loginUserEmail, "Change Password", "Login Password Changed" + LocalDate.now());
                    rs.close();
                    smt.close();
                    this.dispose();
                

            }else{   
            
            JOptionPane.showMessageDialog(this, "Confirm Password Doesn't Match With New Password ", projectTitle, JOptionPane.ERROR_MESSAGE);
                }
            }
            rs.close();
            smt.close();
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex, projectTitle, JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpasswordField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newpasswordField;
    private javax.swing.JPasswordField oldpasswordField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
